# GitHub Actions Workflow with MATLAB Actions
#
# For a general overview of GitHub Actions, see
# https://docs.github.com/en/actions
#
# For using MathWorks products in GitHub Actions, see
# https://github.com/matlab-actions/overview
#
# For details about the syntax of this file, see
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

# Copyright 2021-2023 The MathWorks, Inc.

name: CI using MATLAB

on:
  push:
    branches: [ R2023b ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

  pull_request:
    branches: [ R2023b ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '**.png'
      - '**.svg'
      - '**.txt'
      - '**.xml'

  schedule:
    - cron:  '55/61 20/25 1/6 * *' # schedule a weekly-ish build

  workflow_dispatch:

jobs:

  job-buildtool-23b:

    name: Test in R2023b

    runs-on: ubuntu-latest

    permissions:
      # required for sarif upload
      security-events: write
      checks: write # required for junit test result publishing

    steps:

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          cache: true
          products: |
            Simulink
            Simscape
            Simscape_Electrical
            Simscape_Driveline
            Powertrain_Blockset

      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run buildtool using buildfile.m
        uses: matlab-actions/run-command@v1
        with:
          command: openProject(pwd); buildtool CodeIssues CheckProject Test

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: always()         
        with:
          sarif_file: cache/buildtool-results/code-issues.sarif
          category: matlab-analysis

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always() 
        with:
          report_paths: 'cache/buildtool-results/test-results.xml'

      - name: Upload Test Report  
        if: always() 
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: cache/buildtool-results/test-results.pdf

      - name: Upload All Artifacts 
        if: always() 
        uses: actions/upload-artifact@v2
        with:
          name: All Artifacts
          path: cache/buildtool-results

      - name: Publish coverage
        uses: 5monkeys/cobertura-action@master
        continue-on-error: true
        with:
          path: cache/buildtool-results/code-coverage.xml
          minimum_coverage: 75
